config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => "sessions#new"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users 
  resources :sessions, :only => [:create]
  resources :password_resets

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
####################skip bcoz of fb
# class MyValidator < ActiveModel::Validator

# 	def validate(record)
# 	age = Date.today.year - record.dob.year
# 	age -= 1 if Date.today < record.dob + age.years
# 		if age<18
# 		record.errors[:dob] << 'should be at least 18 Years old'
# 		end
# 	end
# end

# class GoodnessValidator < ActiveModel::Validator

# 	def validate(record)
# 	  em = record.email.split('@').last
# 		unless em == "mobiloitte.com"
# 		 record.errors[:email] << "email should contain @mobiloitte.com"
# 		end
# 	end
# end
###############ends here
require 'carrierwave/orm/activerecord'
class User < ActiveRecord::Base
	#attr_accessible :image_cache

	has_secure_password
	mount_uploader :image, AbhishekUploader

	############skip bcoz of fb 
	# validates :name, exclusion: { in: %w[abhishek,Abhishek] ,
 #                                       message: "%{value} is reserved." }
    
	# validates :email, :name, uniqueness: true
	# validates :name, length: { maximum: 20,
 #                                       too_long: "%{count} characters is the maximum allowed" }

 #    validates :name, format: { with: /\A[a-zA-Z]+\z/,
 #                                        message: "only allows letters" }


 #    #validates :password, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{8,})\z/i,
 #                                        #message: "Should Contains " }
	#  #validates_format_of :password, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
	# validates :password, length: { minimum: 8 }
	# validates  :name,  presence: { case_sensitive: false }
	# validates  :dob, presence: true
	#validates_with MyValidator 
	#validates_with GoodnessValidator 
###############ends here

	#########facebook login
	def self.create_with_omniauth(auth)
        create! do |user|
    p "=======#{auth["provider"]}========#{auth["credentials"]["token"]}======================="
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    #user.password = "abhishek11"
    user.email = auth["info"]["email"]
    user.name = auth["info"]["name"]
    user.image = auth["info"]["image"]
      if auth["provider"].eql?("facebook") || auth["provider"].eql?("twitter")
      return user
       #user.email = auth["info"]["nickname"]
      else
     
      end
  end

  end
	##################fb ends here
	before_create { generate_token(:auth_token) } 

	def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end 
    while User.exists?(column => self[column])
  end
end


def send_password_reset(user)
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!(validate: false)
  UserMailer.send_password_reset(user).deliver_now
end


end

#{}"hey@mycorp.com".split("@").last

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception
helper_method :current_user  

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end
# private 
# def current_user  
#  @current_user ||= User.find_by_auth_token( cookies[:auth_token]) if cookies[:auth_token] 
# end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

	def create
		Rails.logger.info"++++++++++++++#{params.inspect}"
		user = User.find_by_email(params[:email])
		user.send_password_reset(user) if user

		redirect_to root_url, :notice => "Email sent with password reset instructions."
	end

	# def edit
	# 	#@user = User.find_by_password_reset_token!(params[:id])
	# 	@user = User.find_by_id(params[:id])
	# end
	def edit  
        @user = User.find_by_password_reset_token!(params[:id])  
    end  

	# def update
	# 	# @user = User.find_by_password_reset_token!(params[:id])
	# 	# if @user.password_reset_sent_at < 2.hours.ago
	# 	# redirect_to new_password_reset_path, :alert => "Password &crarr; 
	# 	# reset has expired."
	# 	# elsif @user.update_attributes(params[:user])
	# 	# redirect_to root_url, :notice => "Password has been reset."
	# 	# else
	# 	# render :edit
	# 	# end
 #    @user = User.find_by_id(params[:id])

 #     if @user.update_attributes(users_params)
 #       redirect_to user_path, notice: 'Profile has been successfully updated'
 #     end
 # end
	
# private
# 	def users_params
# 	  params.require(:user).permit( :password)
# 	end
    def update  
        @user = User.find_by_password_reset_token!(params[:id])  
        if  @user.password_reset_sent_at < 48.hours.ago  
            redirect_to new_password_reset_path, :alert => "Password ↵   
            reset has expired."  
        elsif @user.update_attributes(users_params)  
            redirect_to root_url, :notice => "Password has been reset."  
        else  
            render :edit  
        end  
    end 
    private
 	def users_params
 	    params.require(:user).permit( :password)
 	end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
  p "----------------#{current_user.inspect}--------------"
   if current_user!=nil
      redirect_to user_path(current_user.id) 
   end
  end
#########fb
 def create
   p "======================#{request.env["omniauth.auth"].inspect}======================================="
   user = User.find_by_email(params[:email])
     if user && user.authenticate(params[:password])
       session[:user_id] = user.id  
      redirect_to user_path(user)
        elsif 
          auth = request.env["omniauth.auth"]
          session[:fb_token] = auth["credentials"]["token"] if auth['provider'] == 'facebook'
          p "=====#{auth.inspect}========"
          user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
          session[:user_id] = user.id
          redirect_to user_path(user), :notice => "Signed in!"
           else
            flash[:notice] = "Invalid Username or Password"
            render "new"
         end
      end 
###########ends
  def destroy
   #reset_session
    if session[:fb_token].present? 
      redirect_to "https://www.facebook.com/logout.php?next=#{"http://localhost:3000"}&access_token=#{session[:fb_token]}" , :notice => "Logged out from fb!"
      session.clear
    else
      p "1111111111111111111111111111111111111111111"
     
      session[:user_id] = nil
      redirect_to root_url, :notice => "Logged out!"
    end
     
  end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def new
	  @user = User.new
 end

 def create
		@user = User.new(users_params)
	   if @user.save
       flash[:notice] = "successfully SignedUp"
	     redirect_to root_path
	      else
		      render 'new'
	    end
 end

 def show
    @user = User.find(params[:id])
  end
 def index
    @users = User.all
  end

 def edit
    @user = User.find(params[:id])
 end

 def update
    @user = User.find(params[:id])
     if @user.update_attributes(users_params)
        flash[:notice] = "Profile updated"
        @user = User.find(params[:id])
          if @user.id == current_user.id
            redirect_to user_path, notice: 'Profile has been successfully updated'
              else 
                 redirect_to users_path, notice: 'Profile has been successfully updated'
         end
     end
 end

 def destroy
 	  @user = User.find(params[:id])
      if @user.destroy
      	 flash[:notice]= 'User has been deleted..'
      	redirect_to users_path
      end
  end

 private
	 def users_params
	    params.require(:user).permit(:name, :email, :password, :dob, :image, :image_cache)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= link_to 'signUP' ,signup_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finaletest</title>
The time now is <%= Time.now %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<%#= link_to image_tag("7.jpg", :width =>1500, :height =>100) %>
<%#= link_to image_tag("index.jpeg", :width =>1500, :height =>200) %>
   <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
   <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
</head>
<body>

	 <div id="user_nav", style = "float: right;">  
     <b> <% if current_user %>  

        Logged in as <%= current_user.email %> </b> 
        <%#= link_to 'Edit', edit_user_path(@user) %> 
        <%= link_to "Profile",user_path(current_user)%>  |
        <%#= link_to 'All Users', users_path %> |
        <%= link_to "Log out", logout_path %>  | 

        <%#= link_to 'Home', user_blogs_path(current_user) %> 
        
        <%#= link_to "Recent Users List",users_path%> 
      <% else %>  
        <%= link_to "Sign up", signup_path %> |   
        <%= link_to "Log in", login_path %> 
        |<%= link_to "Sign in with Facebook", "/auth/facebook" %> |
        <%= link_to "Sign in with Twitter", "/auth/twitter" %>
       <% end %>  
    </div>
<p class="notice"><%= notice %></p>
<%= yield %>

</body>

</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Wana Reset Password!Enter ur Email</h1>
<%= form_tag password_resets_path, :method => :post do %>
<%= label_tag :email %>
<%= text_field_tag :email, params[:email] %>
<%= submit_tag "Reset Password" %></div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%= form_for @user do |f|%>
  <% if @user.errors.any? %>
  
      <h2>Form is invalid</h2>  
      
        <% for message in @user.errors.full_messages %>  
          <li><%= message %></li>  
        <% end %>  
       
     
  <% end %>
   <p>  
    <%= f.label :name %><br />  
    <%= f.text_field :name %>  
  </p>
  <p>  
    <%= f.label :email %><br />  
    <%= f.text_field :email %>  
  </p>    
   <p>  
    <%= f.label :password %><br />  
    <%= f.text_field :password %>  
  </p> 
  <p>  
    <%= f.label :dob %> <br/>  
    <%#= f.text_field :dob, :id=>"datepicker"%>
<%= f.date_select(:dob,:start_year => 1980)%> <br/>
  </p>  
  <%= f.submit "Update" %></p>  

  
<% end %>  

app/views/users/edita.html.erb
<h1>Editing user</h1>
<%= form_for @user do |f|%>
  <% if @user.errors.any? %>
  
      <h2>Form is invalid</h2>  
      
        <% for message in @user.errors.full_messages %>  
          <li><%= message %></li>  
        <% end %>  
       
     
  <% end %>
   <p>  
    <%= f.label :name %><br />  
    <%= f.text_field :name %>  
  </p>
  <p>  
    <%= f.label :email %><br />  
    <%= f.text_field :email %>  
  </p>    
   <p>  
    <%= f.label :password %><br />  
    <%= f.text_field :password %>  
  </p> 
  <p>  
    <%= f.label :dob %> <br />  
    <%=  f.date_select(:dob)%>  
  </p>  
  <%= f.submit "Update" %></p>  
<% end %>  

app/views/users/index.html.erb
 
<% @users.each do |user| %>
 <% if current_user.name == user.name %>
    <%  next %>
     <% end %>
 <h4>Email: <%= user.email %></br></h4>
 <h4>Username: <%= user.name %> </br></h4>
 <h4>Date Of Birth: <%= user.dob %></br></h4>
 <% if (current_user.admin_user == true)%>

  <h4><%= link_to "Edit User" ,edit_user_path(user)%> </h4>
  <h4><%= link_to 'Delete User', user_path(user),
                    method: :delete, data: { confirm: 'Are you sure?' } %></h4>  


 <% end %> 
 <% end %>
 <%= link_to 'Back', user_path(current_user) %>
<%= link_to 'Logout', logout_path %>

app/views/users/new.html.erb
<h1>Sign Up Form </h1>
	
<% if @user.errors.any? %>
	<div>
		<div>
			 The form contains <%= pluralize(@user.errors.count,
			  "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
					<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<%= form_for @user, :html => {:multipart => true}, url: users_path do |f| -%> 
    <p>
       <%= f.label :name %>
	   <%= f.text_field :name %><br/>
	</br>
	</p>
	<p>
	  	 <%= f.label :email %>
	    <%= f.text_field :email %><br/>
	</p>
	</br>
	<p>
	  <%= f.label :password %>
	  <%= f.password_field :password %><br/>
	</p>
	</br>
	<p>
 	    <%= f.label :dob %>
        <%= f.date_select(:dob,:start_year => 1990) %><br/>
	</p>
</br>
	<p>
	  <%= f.label :image,"Upload Image" %>
	  <%= image_tag(@user.image_url) if @user.image? %>
    
    <%#= f.hidden_field :image_cache %>
	    <%= f.file_field :image %>
	</p>
</br>
	
  
	  <%#= f.text_field :dob, :id=>"datepicker"%>
	 
		<%= f.submit %>

	<% end %>

<p>


</p>

app/views/users/show.html.erb
<p><h1>Hi <%= @user.name %> </h1>That's Ur Details</p>
Name:<%= @user.name %><br>
Email:<%= @user.email %><br>
Dob:<%= @user.dob %><br>
<p>

<%#= image_tag(@user.image_url(:small_thumb).to_s)  %>
<%#= image_tag(@user.image.url(:banner))  %>
<%#= image_tag(@user.image.url(:thumb1))  %>
<%#= image_tag painting.image_url(:thumb).to_s %>

<%#= image_tag @user.image.url((:thumbnail),:alt => "Sample Image") %>
<%#= image_tag @user.image.url(:mini_thumbnail) %>
<%= image_tag (@user.image.url(:detail)) %>

</p>
<%= link_to 'Logout', logout_path %>
<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'All Users', users_path %>